# Generated by Django 5.2.4 on 2025-09-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_useremp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='location',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobs',
            name='price',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useremp',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
