# Generated by Django 5.2.4 on 2025-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='related_id',
            field=models.IntegerField(unique=True),
        ),
    ]
