# Generated by Django 5.2.4 on 2025-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cv_related_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremp',
            name='user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
