# Generated by Django 5.2.5 on 2025-08-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('price', models.FloatField()),
                ('category', models.CharField()),
                ('img', models.CharField()),
            ],
        ),
    ]
