# Generated by Django 5.2.4 on 2025-08-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_userproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
