# Generated by Django 5.2.4 on 2025-09-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='employer',
            field=models.IntegerField(),
        ),
    ]
