# Generated by Django 5.2.4 on 2025-09-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_jobs_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='isEmployer',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
